name: Published release

on:
  release:
    types: [published]

jobs:

  checkout_code:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true

  publish_artifacts:
    needs: checkout_code
    uses: ./.github/workflows/publish_artifacts.yml
    with:
      app_name: "timvw-hello-rs"
      tag_name: ${{ github.event.release.tag_name }}
      commitish: ${{ github.event.release.target_commitish }}
    secrets:
      CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
      COMMITTER_TOKEN: ${{ secrets.COMMITTER_TOKEN }}
