name: Test

on:
  workflow_dispatch:
    inputs:
      crate-version:
        description: 'The git tag name to bump the formula to'
        required: true

jobs:
  homebrew:
    name: Bump Homebrew formula
    runs-on: ubuntu-latest
    steps:
      - uses: mislav/bump-homebrew-formula-action@v2
        with:
          homebrew-tap: timvw/homebrew-tap
          base-branch: master
          formula-name: hellors-bin
          tag-name: ${{ github.event.inputs.crate-version }}
          download-url: https://github.com/timvw/hello-rs/releases/download/${{ github.event.inputs.crate-version }}/hello-rs-${{ github.event.inputs.crate-version }}-x86_64-apple-darwin-generic.tar.gz
        env:
          COMMITTER_TOKEN: ${{ secrets.COMMITTER_TOKEN }}